name: angle_detector
description: A Flutter widget that calculates the angle (in radians) between its center and the user's touch position.
version: 0.0.2

repository: https://github.com/adbonnin/flutter_angle_detector
issue_tracker: https://github.com/adbonnin/flutter_angle_detector/issues

topics:
  - angle
  - gesture
  - touch

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
